### ISSUE TITLE
clap plugin variant missing

### ISSUE THREAD

**Issue by falkTX** [flathub/org.freedesktop.LinuxAudio.Plugins.Cardinal#20]
clap is supported as plugin format in cardinal since a few releases, but this repo does not use it

**Comment by ColinKinloch** [comment]
It's present at `/app/extensions/Plugins/Cardinal/lib/clap/` but not being linked to the search path.
It should be fixed by #21.
What software would you suggest for testing this?
Thanks for reporting.

**Comment by falkTX** [comment]
qtractor can load clap, carla too if from git (not the 2.5.x stable series)
